#(wal -t -r &)

export ZSHA_BASE=$HOME/.dotfiles/zsh_config

ZPLUG_HOME=$ZSHA_BASE/zplug

# Install zplug if not installed
if [[ ! -d $ZPLUG_HOME ]]; then
  git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi

# Install vim-plug if not installed
if [[ ! -d ~/.local/share/nvim ]]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

source $ZSHA_BASE/config/aliases
source $ZSHA_BASE/config/env_variables
source $ZSHA_BASE/config/setopts
source $ZSHA_BASE/config/omz_config
source $ZPLUG_HOME/init.zsh

# Allow zplug self management
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug "zsh-users/zsh-history-substring-search"

# Supports oh-my-zsh plugins and the like
zplug "plugins/git",   from:oh-my-zsh

zplug 'denysdovhan/spaceship-zsh-theme', as:theme

# Then, source plugins and add commands to $PATH
zplug load

source $ZSHA_BASE/config/spaceship
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

xrdb ~/.Xresources
